# Generated by Django 5.0.7 on 2024-07-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_event_description_moment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='moment',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterField(
            model_name='moment',
            name='date_time',
            field=models.DateTimeField(verbose_name='Date & Time'),
        ),
    ]
