# Generated by Django 5.0.7 on 2024-07-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_asset_alter_moment_options_alter_moment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assets',
            field=models.ManyToManyField(to='main_app.asset'),
        ),
    ]
